/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autoescola.view;

import autoescola.controleDao.ControleExame;
import autoescola.modelo.bean.Funcionario;
import autoescola.view.tabelas.Tabela;
import autoescola.modelo.bean.Cliente;
import autoescola.modelo.bean.Exame;
import autoescola.modelo.bean.Veiculo;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;

/**
 *
 * @author felipe
 */
public class TelaAgendarExame extends javax.swing.JDialog {

    /**
     * Creates new form TelaAgendarExame
     */
    //private final ControleLogin controleLogin = new ControleLogin();
    private final ControleExame controleExame;
    private final Tabela tabelaAluno = new Tabela();
    private final Tabela tabelaInstrutor = new Tabela();
    private final Tabela tabelaClienteExame = new Tabela();
    private final Tabela tabelaVeiculo = new Tabela();

    public TelaAgendarExame(java.awt.Frame parent, boolean modal, Exame exame) {
        super(parent, modal);
        controleExame = new ControleExame(exame);

        initComponents();
        if (!exame.getDataExame().equals("") && exame.getCodigoExame() == 0) {
            txtDataExame.setText(exame.getDataExame());
        }
        if (exame.getCodigoExame() != 0) {
            Exame e = controleExame.exameEditar();
            txtDataExame.setText(e.getDataExame());
            txtHoraInicio.setText(e.getHorarioInicio());
            txtHoraFim.setText(e.getHorarioFim());
            lblAgendarExame.setText("Editar exame");
            inicializarInstrutor();
            inicializarVeiculo();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jtAlunos = new javax.swing.JTabbedPane();
        jpUsuario = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        txtHoraInicio = new javax.swing.JFormattedTextField();
        jLabel34 = new javax.swing.JLabel();
        txtHoraFim = new javax.swing.JFormattedTextField();
        txtDataExame = new javax.swing.JFormattedTextField();
        jLabel27 = new javax.swing.JLabel();
        bntCadastrarAlterarExame = new javax.swing.JPanel();
        lblAgendarExame = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        bntAdicionarAluno = new javax.swing.JPanel();
        lblCadastrarEndereco = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlunosExame = tabelaClienteExame;
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableAluno = tabelaAluno;
        txtPesquisarAluno = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        bntRemoverAluno = new javax.swing.JPanel();
        lblCadastrarEndereco1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtModelo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JFormattedTextField();
        txtAno = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableVeiculo = tabelaVeiculo;
        bntAdicionarInstrutor2 = new javax.swing.JPanel();
        lblVeiculo = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jbVeiculo = new javax.swing.JComboBox<>();
        txtPesquisarVeiculo = new javax.swing.JTextField();
        txtCapacidade = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableInstrutor = tabelaInstrutor;
        jbInstrutor = new javax.swing.JComboBox<>();
        txtPesquisarInstrutor = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        bntAdicionarInstrutor = new javax.swing.JPanel();
        lblCadastrarInstrutor = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtNome = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        txtRg = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        txtHoraSai = new javax.swing.JFormattedTextField();
        txtHoraEntra = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jcCategoria = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        txtCarteiraMotorista = new javax.swing.JFormattedTextField();
        jLabel38 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(144, 180, 242));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("Exame");

        jtAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtAlunosMouseClicked(evt);
            }
        });

        jpUsuario.setBackground(new java.awt.Color(254, 254, 254));

        jLabel25.setText("Hora fim do exame:");

        txtHoraInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        jLabel34.setText("Hora inicio do exame:");

        txtHoraFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        txtDataExame.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jLabel27.setText("Data do exame:");

        bntCadastrarAlterarExame.setBackground(new java.awt.Color(28, 181, 165));
        bntCadastrarAlterarExame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntCadastrarAlterarExame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntCadastrarAlterarExameMouseClicked(evt);
            }
        });

        lblAgendarExame.setBackground(new java.awt.Color(254, 254, 254));
        lblAgendarExame.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblAgendarExame.setForeground(new java.awt.Color(254, 254, 254));
        lblAgendarExame.setText("Agendar Exame");

        javax.swing.GroupLayout bntCadastrarAlterarExameLayout = new javax.swing.GroupLayout(bntCadastrarAlterarExame);
        bntCadastrarAlterarExame.setLayout(bntCadastrarAlterarExameLayout);
        bntCadastrarAlterarExameLayout.setHorizontalGroup(
            bntCadastrarAlterarExameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bntCadastrarAlterarExameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAgendarExame)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bntCadastrarAlterarExameLayout.setVerticalGroup(
            bntCadastrarAlterarExameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bntCadastrarAlterarExameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAgendarExame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel35.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel35.setText("Formato exemplo: 10/05/2017");

        jLabel36.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel36.setText("Formato exemplo: 11:10");

        jLabel37.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel37.setText("Formato exemplo: 12:10");

        javax.swing.GroupLayout jpUsuarioLayout = new javax.swing.GroupLayout(jpUsuario);
        jpUsuario.setLayout(jpUsuarioLayout);
        jpUsuarioLayout.setHorizontalGroup(
            jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpUsuarioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bntCadastrarAlterarExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpUsuarioLayout.createSequentialGroup()
                        .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDataExame)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jpUsuarioLayout.createSequentialGroup()
                                    .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel34)
                                        .addComponent(jLabel36))
                                    .addGap(33, 33, 33)
                                    .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel37)
                                        .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel25)
                                            .addComponent(txtHoraFim)))))
                            .addComponent(jLabel35))
                        .addGap(0, 426, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpUsuarioLayout.setVerticalGroup(
            jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, Short.MAX_VALUE)
                .addComponent(bntCadastrarAlterarExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jtAlunos.addTab("Exame", jpUsuario);

        jPanel11.setBackground(new java.awt.Color(254, 254, 254));

        bntAdicionarAluno.setBackground(new java.awt.Color(28, 181, 165));
        bntAdicionarAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntAdicionarAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntAdicionarAlunoMouseClicked(evt);
            }
        });

        lblCadastrarEndereco.setBackground(new java.awt.Color(254, 254, 254));
        lblCadastrarEndereco.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblCadastrarEndereco.setForeground(new java.awt.Color(254, 254, 254));
        lblCadastrarEndereco.setText("Adicionar Aluno");

        javax.swing.GroupLayout bntAdicionarAlunoLayout = new javax.swing.GroupLayout(bntAdicionarAluno);
        bntAdicionarAluno.setLayout(bntAdicionarAlunoLayout);
        bntAdicionarAlunoLayout.setHorizontalGroup(
            bntAdicionarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bntAdicionarAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadastrarEndereco)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        bntAdicionarAlunoLayout.setVerticalGroup(
            bntAdicionarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bntAdicionarAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadastrarEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTableAlunosExame.setModel(controleExame.consultarAlunosExame() );
        jTableAlunosExame.getTableHeader().setReorderingAllowed(false);
        jTableAlunosExame.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableAlunosExameKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAlunosExame);

        jTableAluno.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTableAluno.setModel(controleExame.consultarAlunos());
        jTableAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAlunoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableAluno);

        txtPesquisarAluno.setBackground(new java.awt.Color(254, 254, 254));
        txtPesquisarAluno.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtPesquisarAluno.setForeground(new java.awt.Color(1, 1, 1));
        txtPesquisarAluno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(144, 180, 242), 1, true));
        txtPesquisarAluno.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtPesquisarAlunoInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtPesquisarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarAlunoActionPerformed(evt);
            }
        });
        txtPesquisarAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarAlunoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarAlunoKeyReleased(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(254, 254, 254));
        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(1, 1, 1));
        jLabel13.setText("Pesquisar:");

        jComboBox1.setBackground(new java.awt.Color(254, 254, 254));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "codigo", "nome", "rg", "cpf", "numero do Ladv" }));
        jComboBox1.setBorder(null);

        jLabel4.setText("* É necessário que o exame esteja cadastrado");

        bntRemoverAluno.setBackground(new java.awt.Color(28, 181, 165));
        bntRemoverAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntRemoverAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntRemoverAlunoMouseClicked(evt);
            }
        });

        lblCadastrarEndereco1.setBackground(new java.awt.Color(254, 254, 254));
        lblCadastrarEndereco1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblCadastrarEndereco1.setForeground(new java.awt.Color(254, 254, 254));
        lblCadastrarEndereco1.setText("Remover Aluno");

        javax.swing.GroupLayout bntRemoverAlunoLayout = new javax.swing.GroupLayout(bntRemoverAluno);
        bntRemoverAluno.setLayout(bntRemoverAlunoLayout);
        bntRemoverAlunoLayout.setHorizontalGroup(
            bntRemoverAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bntRemoverAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadastrarEndereco1)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        bntRemoverAlunoLayout.setVerticalGroup(
            bntRemoverAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bntRemoverAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadastrarEndereco1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(txtPesquisarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel13))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(bntRemoverAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bntAdicionarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntAdicionarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel13))
                    .addComponent(bntRemoverAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPesquisarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtAlunos.addTab("Alunos", jPanel11);

        jPanel4.setBackground(new java.awt.Color(254, 254, 254));

        txtModelo.setEnabled(false);

        jLabel14.setText("Placa");

        jLabel28.setText("Modelo");

        jLabel29.setText("Capacidade");

        jLabel30.setText("Ano");

        try {
            txtPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AAA-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPlaca.setEnabled(false);

        try {
            txtAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtAno.setEnabled(false);

        jLabel1.setText("* É necessário que o exame esteja cadastrado");

        jPanel7.setBackground(new java.awt.Color(61, 180, 162));

        jTableVeiculo.setModel(controleExame.consultarVeiculosAtivos());
        jScrollPane4.setViewportView(jTableVeiculo);

        bntAdicionarInstrutor2.setBackground(new java.awt.Color(97, 212, 195));
        bntAdicionarInstrutor2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntAdicionarInstrutor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntAdicionarInstrutor2MouseClicked(evt);
            }
        });

        lblVeiculo.setBackground(new java.awt.Color(254, 254, 254));
        lblVeiculo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblVeiculo.setForeground(new java.awt.Color(254, 254, 254));
        lblVeiculo.setText("Adicionar veículo");

        javax.swing.GroupLayout bntAdicionarInstrutor2Layout = new javax.swing.GroupLayout(bntAdicionarInstrutor2);
        bntAdicionarInstrutor2.setLayout(bntAdicionarInstrutor2Layout);
        bntAdicionarInstrutor2Layout.setHorizontalGroup(
            bntAdicionarInstrutor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bntAdicionarInstrutor2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVeiculo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bntAdicionarInstrutor2Layout.setVerticalGroup(
            bntAdicionarInstrutor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bntAdicionarInstrutor2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel33.setBackground(new java.awt.Color(254, 254, 254));
        jLabel33.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(254, 254, 254));
        jLabel33.setText("Pesquisar veiculos disponiveis:");

        jbVeiculo.setBackground(new java.awt.Color(254, 254, 254));
        jbVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "codigo do veiculo", "placa", "ano", "modelo", "capacidade" }));
        jbVeiculo.setBorder(null);

        txtPesquisarVeiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarVeiculoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(txtPesquisarVeiculo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntAdicionarInstrutor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPesquisarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bntAdicionarInstrutor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtCapacidade.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(244, 244, 244))
                        .addComponent(txtPlaca)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(429, 429, 429))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtAno, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtModelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel28))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel29)
                                .addComponent(txtCapacidade, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)))))
                .addContainerGap(418, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jtAlunos.addTab("Veículo", jPanel4);

        jPanel10.setBackground(new java.awt.Color(254, 254, 254));

        jPanel5.setBackground(new java.awt.Color(61, 180, 162));

        jTableInstrutor.setModel(controleExame.consultarInstrutoresAtivos());
        jScrollPane2.setViewportView(jTableInstrutor);

        jbInstrutor.setBackground(new java.awt.Color(254, 254, 254));
        jbInstrutor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "codigo", "rg", "cpf", "nome" }));
        jbInstrutor.setBorder(null);

        txtPesquisarInstrutor.setBackground(new java.awt.Color(254, 254, 254));
        txtPesquisarInstrutor.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtPesquisarInstrutor.setForeground(new java.awt.Color(1, 1, 1));
        txtPesquisarInstrutor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(144, 180, 242), 1, true));
        txtPesquisarInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarInstrutorActionPerformed(evt);
            }
        });
        txtPesquisarInstrutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarInstrutorKeyReleased(evt);
            }
        });

        jLabel32.setBackground(new java.awt.Color(254, 254, 254));
        jLabel32.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(254, 254, 254));
        jLabel32.setText("Pesquisar instrutor disponivel:");

        bntAdicionarInstrutor.setBackground(new java.awt.Color(97, 212, 195));
        bntAdicionarInstrutor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntAdicionarInstrutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntAdicionarInstrutorMouseClicked(evt);
            }
        });

        lblCadastrarInstrutor.setBackground(new java.awt.Color(254, 254, 254));
        lblCadastrarInstrutor.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblCadastrarInstrutor.setForeground(new java.awt.Color(254, 254, 254));
        lblCadastrarInstrutor.setText("Adicionar Instrutor");

        javax.swing.GroupLayout bntAdicionarInstrutorLayout = new javax.swing.GroupLayout(bntAdicionarInstrutor);
        bntAdicionarInstrutor.setLayout(bntAdicionarInstrutorLayout);
        bntAdicionarInstrutorLayout.setHorizontalGroup(
            bntAdicionarInstrutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bntAdicionarInstrutorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadastrarInstrutor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bntAdicionarInstrutorLayout.setVerticalGroup(
            bntAdicionarInstrutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bntAdicionarInstrutorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadastrarInstrutor, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtPesquisarInstrutor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(bntAdicionarInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bntAdicionarInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPesquisarInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(254, 254, 254));

        jLabel11.setText("Nome");

        txtNome.setEnabled(false);

        jLabel16.setText("RG");

        jLabel22.setText("Horario de saída:");

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelular.setEnabled(false);

        jLabel21.setText("Horario de entrada:");

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setEnabled(false);

        jLabel20.setText("Celular:");

        jLabel19.setText("Telefone:");

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setEnabled(false);

        try {
            txtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRg.setEnabled(false);

        jLabel17.setText("CPF");

        try {
            txtHoraSai.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHoraSai.setEnabled(false);

        try {
            txtHoraEntra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHoraEntra.setEnabled(false);

        jLabel2.setText("* É necessário que o exame esteja cadastrado");

        jcCategoria.setBackground(new java.awt.Color(254, 254, 254));
        jcCategoria.setEditable(true);
        jcCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        jcCategoria.setEnabled(false);

        jLabel31.setText("Categoria");

        try {
            txtCarteiraMotorista.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCarteiraMotorista.setEnabled(false);

        jLabel38.setText("Carteira de motorista:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(12, 12, 12))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addGap(220, 220, 220)
                            .addComponent(jLabel17))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRg)
                                    .addComponent(jLabel19)
                                    .addComponent(txtTelefone)
                                    .addComponent(txtHoraEntra, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel21))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCpf, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCelular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                .addComponent(txtHoraSai)))
                        .addComponent(txtNome))
                    .addComponent(jLabel11))
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtCarteiraMotorista)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(205, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCarteiraMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoraEntra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraSai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtAlunos.addTab("Instrutor", jPanel10);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jtAlunos))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 975, 684);
    }// </editor-fold>//GEN-END:initComponents

    private void bntAdicionarAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntAdicionarAlunoMouseClicked
        int row = jTableAluno.getSelectedRow();
        if (row != -1) {
            String id = String.valueOf(jTableAluno.getValueAt(row, 0));

            if (controleExame.adicionarAlunoExame(parseInt(id))) {
                jTableAluno.setModel(controleExame.consultarAlunos());

                jTableAlunosExame.setModel(controleExame.consultarAlunosExame());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não existem alunos selecionados!");

        }

    }//GEN-LAST:event_bntAdicionarAlunoMouseClicked

    private void jTableAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAlunoMouseClicked

    }//GEN-LAST:event_jTableAlunoMouseClicked

    private void txtPesquisarAlunoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtPesquisarAlunoInputMethodTextChanged

    }//GEN-LAST:event_txtPesquisarAlunoInputMethodTextChanged

    private void txtPesquisarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarAlunoActionPerformed

    }//GEN-LAST:event_txtPesquisarAlunoActionPerformed

    private void txtPesquisarAlunoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarAlunoKeyPressed
        //jTableAluno.setModel(controleExame.consultaAlunoLikeExame(txtPesquisarAluno, jComboBox1));
    }//GEN-LAST:event_txtPesquisarAlunoKeyPressed

    private void txtPesquisarAlunoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarAlunoKeyReleased
        jTableAluno.setModel(controleExame.consultaAlunoLikeExame(txtPesquisarAluno, jComboBox1));


    }//GEN-LAST:event_txtPesquisarAlunoKeyReleased

    private void jtAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtAlunosMouseClicked

    }//GEN-LAST:event_jtAlunosMouseClicked


    private void bntCadastrarAlterarExameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntCadastrarAlterarExameMouseClicked
        Exame exame = new Exame();
        exame.setDataExame(txtDataExame.getText());
        exame.setHorarioInicio(txtHoraInicio.getText());
        exame.setHorarioFim(txtHoraFim.getText());
        if (!controleExame.temExame()) {

            if (controleExame.agendarExame(exame)) {
                jTableAluno.setModel(controleExame.consultarAlunos());
            }
        } else {
            if (controleExame.alterarExame(exame)) {
                // jTableAluno.setModel(controleExame.consultarAlunos());
            }
        }
    }//GEN-LAST:event_bntCadastrarAlterarExameMouseClicked

    private void inicializarInstrutor() {
        Funcionario funcionario = controleExame.getInstrutor();
        if (funcionario.getCodigoFuncionario() != 0) {
            txtNome.setText(funcionario.getNome());
            txtRg.setText(funcionario.getRg());
            txtCpf.setText(funcionario.getCpf());
            txtTelefone.setText(funcionario.getTelefone());
            txtCelular.setText(funcionario.getCelular());
            txtHoraEntra.setText(funcionario.getHora_entra());
            txtHoraSai.setText(funcionario.getHora_sai());
            txtCarteiraMotorista.setText(funcionario.getNumCarteira());
            jcCategoria.setSelectedItem(funcionario.getCategoria());
            lblCadastrarInstrutor.setText("Alterar instrutor");
        }

    }

    private void inicializarVeiculo() {
        Veiculo veiculo = controleExame.getVeiculo();
        if (veiculo.getCodVeiculo() != 0) {
            txtPlaca.setText(veiculo.getPlaca());
            txtModelo.setText(veiculo.getModelo());
            txtAno.setText(veiculo.getAno());
            txtCapacidade.setText(String.valueOf(veiculo.getCapacidade()));
            lblVeiculo.setText("Alterar Veiculo");
        }

    }


    private void bntAdicionarInstrutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntAdicionarInstrutorMouseClicked
        // controleExame.adicionarInstrutor(
        int row = jTableInstrutor.getSelectedRow();
        if (row != -1) {
            String id = String.valueOf(jTableInstrutor.getValueAt(row, 0));

            if (controleExame.adicionarInstrutor(parseInt(id))) {
                inicializarInstrutor();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não existem instrutor selecionado!");

        }


    }//GEN-LAST:event_bntAdicionarInstrutorMouseClicked

    private void txtPesquisarInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarInstrutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarInstrutorActionPerformed

    private void jTableAlunosExameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableAlunosExameKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_DELETE) {

            int row = jTableAlunosExame.getSelectedRow();
            if (row > -1) {
                int id = parseInt(jTableAlunosExame.getValueAt(row, 0).toString());
                Cliente cli = new Cliente();
                cli.setCodCliente(id);
                if (controleExame.deletarAluno(cli)) {

                    jTableAlunosExame.setModel(controleExame.consultarAlunosExame());
                    jTableAluno.setModel(controleExame.consultarAlunos());
                } else {

                }
            }
        }
    }//GEN-LAST:event_jTableAlunosExameKeyPressed

    private void bntRemoverAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntRemoverAlunoMouseClicked
        int row = jTableAlunosExame.getSelectedRow();
        if (row != -1) {
            int id = parseInt(jTableAlunosExame.getValueAt(row, 0).toString());
            Cliente cli = new Cliente();
            cli.setCodCliente(id);
            if (controleExame.deletarAluno(cli)) {

                jTableAlunosExame.setModel(controleExame.consultarAlunosExame());
                jTableAluno.setModel(controleExame.consultarAlunos());
            } else {

            }
        } else {

            JOptionPane.showMessageDialog(null, "Não existem alunos selecionados!");

        }


    }//GEN-LAST:event_bntRemoverAlunoMouseClicked

    private void txtPesquisarInstrutorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarInstrutorKeyReleased
        jTableInstrutor.setModel(controleExame.consultaFuncionarioLike(txtPesquisarInstrutor, jbInstrutor));
    }//GEN-LAST:event_txtPesquisarInstrutorKeyReleased

    private void bntAdicionarInstrutor2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntAdicionarInstrutor2MouseClicked
        int row = jTableVeiculo.getSelectedRow();
        if (row != -1) {
            String id = String.valueOf(jTableVeiculo.getValueAt(row, 0));

            if (controleExame.adicionarVeiculo(parseInt(id))) {
                inicializarVeiculo();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não existem veiculos selecionados!");

        }

    }//GEN-LAST:event_bntAdicionarInstrutor2MouseClicked

    private void txtPesquisarVeiculoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarVeiculoKeyReleased

        jTableVeiculo.setModel(controleExame.consultaVeiculoLike(txtPesquisarVeiculo, jbVeiculo));

    }//GEN-LAST:event_txtPesquisarVeiculoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAgendarExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAgendarExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAgendarExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAgendarExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Exame exame = new Exame();
                TelaAgendarExame dialog = new TelaAgendarExame(new javax.swing.JFrame(), true, exame);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bntAdicionarAluno;
    private javax.swing.JPanel bntAdicionarInstrutor;
    private javax.swing.JPanel bntAdicionarInstrutor2;
    private javax.swing.JPanel bntCadastrarAlterarExame;
    private javax.swing.JPanel bntRemoverAluno;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableAluno;
    private javax.swing.JTable jTableAlunosExame;
    private javax.swing.JTable jTableInstrutor;
    private javax.swing.JTable jTableVeiculo;
    private javax.swing.JComboBox<String> jbInstrutor;
    private javax.swing.JComboBox<String> jbVeiculo;
    private javax.swing.JComboBox<String> jcCategoria;
    private javax.swing.JPanel jpUsuario;
    private javax.swing.JTabbedPane jtAlunos;
    private javax.swing.JLabel lblAgendarExame;
    private javax.swing.JLabel lblCadastrarEndereco;
    private javax.swing.JLabel lblCadastrarEndereco1;
    private javax.swing.JLabel lblCadastrarInstrutor;
    private javax.swing.JLabel lblVeiculo;
    private javax.swing.JFormattedTextField txtAno;
    private javax.swing.JTextField txtCapacidade;
    private javax.swing.JFormattedTextField txtCarteiraMotorista;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtDataExame;
    private javax.swing.JFormattedTextField txtHoraEntra;
    private javax.swing.JFormattedTextField txtHoraFim;
    private javax.swing.JFormattedTextField txtHoraInicio;
    private javax.swing.JFormattedTextField txtHoraSai;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JFormattedTextField txtNome;
    private javax.swing.JTextField txtPesquisarAluno;
    private javax.swing.JTextField txtPesquisarInstrutor;
    private javax.swing.JTextField txtPesquisarVeiculo;
    private javax.swing.JFormattedTextField txtPlaca;
    private javax.swing.JFormattedTextField txtRg;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
